env:
  es2022: true
  browser: true
  node: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:svelte/recommended
  - prettier

parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'

parserOptions:
  sourceType: 'module'
  extraFileExtensions: ['.svelte']

overrides:
  - files: ['**/*.svelte']
    parser: 'svelte-eslint-parser'
    parserOptions:
      parser: '@typescript-eslint/parser'

rules:
  '@typescript-eslint/no-extra-semi': error
  # '@typescript-eslint/explicit-function-return-type':
  #  - warn
  #  - allowExpressions: true
  # '@typescript-eslint/explicit-module-boundary-types': warn
  '@typescript-eslint/ban-ts-comment': off
  '@typescript-eslint/no-unused-vars':
    - error
    - argsIgnorePattern: '^_'
      varsIgnorePattern: '^_'
      caughtErrorsIgnorePattern: '^_'
      destructuredArrayIgnorePattern: '^_'
  eqeqeq: error
